{
 "title": "Kubernetes Cron and Batch Job monitoring",
 "description": "Consolidated Dashboard for Monitoring All Batch job pods and Cronjob in Kubernetes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "cronjob_name",
    "label": "CronJob",
    "query": {
     "query": "label_values(kube_cronjob_info{namespace=~\"$namespace\"}, cronjob)"
    }
   },
   {
    "name": "job_name",
    "label": "Job",
    "query": {
     "query": "label_values(kube_job_info{namespace=~\"$namespace\"}, job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CronJobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(kube_cronjob_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "BatchJobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active CronJobs ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active{namespace=~\"$namespace\", cronjob=~\"$cronjob_name\"}) by(namespace, cronjob)",
     "legendFormat": "{{ cronjob }}"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\", job_name=~\"$job_name\"}) by(namespace, job_name)",
     "legendFormat": "{{ job_name }}"
    }
   ]
  }
 ]
}