{
 "title": "Kubernetes / Horizontal Pod Autoscaler",
 "description": "A quick and simple dashboard for viewing how your horizontal pod autoscaler is doing.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_hpa_metadata_generation{job=\"kubernetes-service-endpoints\"}, namespace)"
    }
   },
   {
    "name": "hpa",
    "label": "Name",
    "query": {
     "query": "label_values(kube_hpa_labels{job=\"kubernetes-service-endpoints\", namespace=\"$namespace\"}, hpa)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_hpa_status_desired_replicas{job=\"kubernetes-service-endpoints\", namespace=~\"$namespace\", hpa=~\"$hpa\"})"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_hpa_status_current_replicas{job=\"kubernetes-service-endpoints\", namespace=~\"$namespace\", hpa=~\"$hpa\"})"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_hpa_spec_min_replicas{job=\"kubernetes-service-endpoints\",  namespace=~\"$namespace\", hpa=~\"$hpa\"})"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_hpa_spec_max_replicas{job=\"kubernetes-service-endpoints\", hpa=~\"$hpa\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_status_desired_replicas{job=\"kubernetes-service-endpoints\", hpa=~\"$hpa\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ hpa }} (desired)"
    },
    {
     "expr": "kube_hpa_status_current_replicas{job=\"kubernetes-service-endpoints\", hpa=~\"$hpa\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ hpa }} (running)"
    },
    {
     "expr": "kube_hpa_spec_max_replicas{job=\"kubernetes-service-endpoints\", hpa=~\"$hpa\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ hpa }} (max)"
    },
    {
     "expr": "kube_hpa_spec_min_replicas{job=\"kubernetes-service-endpoints\", hpa=~\"$hpa\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ hpa }} (min)"
    }
   ]
  }
 ]
}