{
 "title": "CloudFlare Zone Analytics",
 "description": "Dashboard for Prometheus cloudflare-exporter\r\nhttps://github.com/lablabs/cloudflare-exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": {
     "query": "label_values(cloudflare_zone_requests_total, zone)"
    }
   },
   {
    "name": "regions",
    "query": {
     "query": "label_values(cloudflare_zone_requests_country, region)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[5m])"
    }
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[5m])"
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Uniques / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[5m])"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[5m])",
     "legendFormat": "visitors"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[5m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_requests_cached{zone=~\"$zone\"}[5m])",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Requests per Country / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[5m]) > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"5..\"}[5m]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Errors / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_status{zone=~\"$zone\", status=~\"5..\"}[5m]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_cached{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "(cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_cached{zone=~\"$zone\"}) / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_ssl_encrypted{zone=\"$zone\"} / cloudflare_zone_requests_total{zone=\"$zone\"}",
     "legendFormat": "encrypted"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_content_type{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Bandwidth / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[5m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[5m])",
     "legendFormat": "cached"
    },
    {
     "expr": "rate(cloudflare_zone_bandwidth_uncached{zone=~\"$zone\"}[5m])",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_bandwidth_cached{zone=~\"$zone\"} / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "(cloudflare_zone_bandwidth_total{zone=~\"$zone\"} - cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}) / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Bandwidth Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_content_type{zone=~\"$zone\"}[5m])",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  { "title": "Regions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Requests by Region / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[5m]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Bandwidth by Region / second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (region)(rate(cloudflare_zone_bandwidth_country{zone=~\"$zone\"}[5m]))",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Requests in $regions / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "repeat": "regions",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\", region=~\"$regions\"}[5m]) > 10",
     "legendFormat": "{{ country }}"
    }
   ]
  },
  { "title": "Threats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 } },
  {
   "title": "Threats / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_total{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{zone}}/threats"
    }
   ]
  },
  {
   "title": "Threats / country",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_country{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{country}}/threats"
    }
   ]
  },
  {
   "title": "Threats / type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_threats_type{zone=~\"$zone\"}[1m])",
     "legendFormat": "{{type}}/threats"
    }
   ]
  },
  { "title": "Colocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 } },
  {
   "title": "Requests  by Colocations - $regions / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 223 },
   "repeat": "regions",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_colocation_requests_country{zone=\"$zone\", region=\"$regions\"}[5m]) > 0",
     "legendFormat": "{{country}}/{{ colocation }}"
    }
   ]
  },
  {
   "title": "Cached bandwidth by Colocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 359 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(cloudflare_zone_colocation_bandwidth_cached{zone=\"$zone\"}[5m]) > 0",
     "legendFormat": "{{ colocation }}"
    }
   ]
  }
 ]
}