{
 "title": "PostgreSQL PGbouncer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "db",
    "label": "Db",
    "query": {
     "query": "label_values(pgbouncer_databases_database_current_connections,database)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(pgbouncer_up, app)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pgbouncer_up{app=~\"$deployment\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client active connections $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m]) ) )"
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_databases_database_pool_size{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Databases database reserve pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database) (pgbouncer_databases_database_reserve_pool_size{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database) ( rate(pgbouncer_stats_queries_duration_microseconds_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Stats queries duration $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database, kubernetes_pod_name) ( rate(pgbouncer_stats_queries_duration_microseconds_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m])) / 1000000 )",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name}}: queries duration"
    },
    {
     "expr": "sort_desc( sum by (database, kubernetes_pod_name) ( rate(pgbouncer_stats_waiting_duration_microseconds_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m])) / 1000000 ) ",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name}}: waiting duration"
    }
   ]
  },
  {
   "title": "Transactions stats $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database, kubernetes_pod_name) ( rate(pgbouncer_stats_transactions_duration_microseconds_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m])) / 1000000 )",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name}}: transactions duration (s)"
    },
    {
     "expr": "sort_desc( sum by (database, kubernetes_pod_name) ( rate(pgbouncer_stats_transactions_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m]) ) )",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name}}: transactions total"
    }
   ]
  },
  {
   "title": "Pgbouncer pools connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\", app=~\"$deployment\",  kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name }}: Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name }}: Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Server login connections"
    },
    {
     "expr": "pgbouncer_databases_database_current_connections{database=~\"$db\", app=~\"$deployment\", kubernetes_name=~\"$pod\"}",
     "legendFormat": "{{ database }}: Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database,kubernetes_pod_name) ( rate(pgbouncer_stats_received_bytes_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m])*8 ) )",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name }}: received bytes total"
    },
    {
     "expr": "sort_desc( sum by (database,kubernetes_pod_name) ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$db\", app=~\"$deployment\", kubernetes_pod_name=~\"$pod\"}[1m])*8 ) )",
     "legendFormat": "{{ database }} - {{ kubernetes_pod_name }}: sent bytes total"
    }
   ]
  }
 ]
}