{
 "title": "Node.js Exporter Dashboard",
 "description": "Prometheus Node.js Exporter dashboard",
 "tags": [
  "node.js",
  "nodejs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(nodejs_eventloop_lag_seconds, app)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(nodejs_eventloop_lag_seconds{app=~\"$app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_eventloop_lag_seconds{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "singlestat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval]) * 100",
     "legendFormat": "System CPU - {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval]) * 100",
     "legendFormat": "Total CPU - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "graph",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Process Memory - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Heap Total - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Heap Used - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "External Memory - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "graph",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Active Handler - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_active_requests_total{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Active Request - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Last - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "P99 - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "P50 - {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "GC Duration Rate",
   "type": "graph",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kind}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kind}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Total - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Used - {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_resident_memory_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Resident - {{kubernetes_pod_name}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "External - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - {{kind}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kind}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{app=~\"$app\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{space}} - {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}